### PR TITLE
fix R CMD CHECK note

### PR DESCRIPTION
**Pull request by pawelru**
```
* checking package dependencies ... NOTE
Vignette dependency required without any vignettes: ‘knitr’
```

### CODE REVIEW

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by donyunardi — CHANGES_REQUESTED** [review]
Might as well fix this note by adding SECURITY.md to .Rbuildignore?

```
❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘SECURITY.md’
```

**Comment by pawelru** [comment]
Thanks. Fixed this as well as the one about title case (turned on only for `--as-cran`)

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by donyunardi — APPROVED** [review]

**Pull request merged**
